apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-v1
  labels:
    app: go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: ramjirv3217/go-gin-api:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: go-server-volume
          mountPath: /etc/config
        env:
         - name: DB-PORT
           valueFrom:
              configMapKeyRef:
                 name: test-cm
                 key: db-port
         - name: PORT
           valueFrom:
              configMapKeyRef:
                 name: test-cm
                 key: PORT
        ports:
        - containerPort: 14000
      volumes:
      - name: go-server-volume
        configMap:
          name: test-cm